var TestConfig = {
      "TestName": "Expected Trend of Conversation Traits",
      "RateScalePng": "img/alignment.png",
      "RateScaleBgPng": "img/scale_abs_background.png",
      "RateMinValue": 0,
      "RateMaxValue": 100,
      "RateDefaultValue":50,
      "ShowFileIDs": false,
      "ShowResults": false,
      "LoopByDefault": false,
      "EnableABLoop": true,
      "EnableOnlineSubmission": false,
      "BeaqleServiceURL": "/web_service/beaqleJS_Service.php",
      "SupervisorContact": "shoinoue@link.cuhk.edu.cn",
      "RandomizeTestOrder": true,
      "MaxTestsPerRun": 15,
      "RequireMaxRating": false,
      "AudioRoot": "",
      "Testsets":
    [
  {
    "Name": "Target Personality: Openness",
    "TestID": "Openness",
    "Text": "Please relate the personality <b>Openness</b> to conversation traits. You are required to answer whether each conversation trait (e.g. Frequent Laughter) is aligned with <b>Openness</b>.<br><br><b>Target Personality</b>: Openness<br><b>Explanation to 'Openness'</b>: intellectual, imaginative, independent-minded<br><b>Opposite Term</b>: 'Closeness'",
    "Files": {
      "<b>Frequent Taking Turns: </b>Indicates that the speaker often takes turns when there is an opportunity to speak.": "./audio/sample.wav",
      "<b>Long Talking Time per Turn: </b>Indicates that the speaker tends to talk for a long time before stopping or being interrupted.": "./audio/sample.wav",
      "<b>Frequent Laughter: </b>Indicates that laughter occurs often during the conversation (e.g., many laughs per minute).": "./audio/sample.wav",
      "<b>Frequent Emotive Backchannel: </b>Indicates that the speaker often provides emotional feedback (e.g., 'Wow!') while another person is talking.": "./audio/sample.wav",
      "<b>Frequent Cognitive Backchannel: </b>Indicates that the speaker often provides cognitive feedback (e.g., 'Oh, I see') while another person is talking.": "./audio/sample.wav",
      "<b>Frequent Interjections: </b>Indicates that there are many attempts to interrupt (both successful and unsuccessful interjections).": "./audio/sample.wav",
      "<b>Frequent Positive Sentiment: </b>Indicates a tendency to frequently use positive language.": "./audio/sample.wav",
      "<b>Frequent Neutral Sentiment: </b>Indicates a tendency to frequently use neutral language.": "./audio/sample.wav",
      "<b>Frequent Negative Sentiment: </b>Indicates a tendency to frequently use negative language.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Anger): </b>Indicates a tendency to frequently show anger in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Disgust): </b>Indicates a tendency to frequently show disgust in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Fear): </b>Indicates a tendency to frequently show fear in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Joy): </b>Indicates a tendency to frequently show joy in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Neutral): </b>Indicates a tendency to frequently remain neutral in emotional tone.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Sadness): </b>Indicates a tendency to frequently show sadness in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Surprise): </b>Indicates a tendency to frequently show surprise in speech.": "./audio/sample.wav",
    }
  },
  {
    "Name": "Target Personality: Conscientiousness",
    "TestID": "Conscientiousness",
    "Text": "Please relate the personality <b>Conscientiousness</b> to conversation traits. You are required to answer whether each conversation trait (e.g. Frequent Laughter) is aligned with <b>Conscientiousness</b>.<br><br><b>Target Personality</b>: Conscientiousness<br><b>Explanation to 'Conscientiousness'</b>: orderly, responsible, dependable<br><b>Opposite Term</b>: 'Lack of direction'",
    "Files": {
      "<b>Frequent Taking Turns: </b>Indicates that the speaker often takes turns when there is an opportunity to speak.": "./audio/sample.wav",
      "<b>Long Talking Time per Turn: </b>Indicates that the speaker tends to talk for a long time before stopping or being interrupted.": "./audio/sample.wav",
      "<b>Frequent Laughter: </b>Indicates that laughter occurs often during the conversation (e.g., many laughs per minute).": "./audio/sample.wav",
      "<b>Frequent Emotive Backchannel: </b>Indicates that the speaker often provides emotional feedback (e.g., 'Wow!') while another person is talking.": "./audio/sample.wav",
      "<b>Frequent Cognitive Backchannel: </b>Indicates that the speaker often provides cognitive feedback (e.g., 'Oh, I see') while another person is talking.": "./audio/sample.wav",
      "<b>Frequent Interjections: </b>Indicates that there are many attempts to interrupt (both successful and unsuccessful interjections).": "./audio/sample.wav",
      "<b>Frequent Positive Sentiment: </b>Indicates a tendency to frequently use positive language.": "./audio/sample.wav",
      "<b>Frequent Neutral Sentiment: </b>Indicates a tendency to frequently use neutral language.": "./audio/sample.wav",
      "<b>Frequent Negative Sentiment: </b>Indicates a tendency to frequently use negative language.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Anger): </b>Indicates a tendency to frequently show anger in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Disgust): </b>Indicates a tendency to frequently show disgust in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Fear): </b>Indicates a tendency to frequently show fear in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Joy): </b>Indicates a tendency to frequently show joy in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Neutral): </b>Indicates a tendency to frequently remain neutral in emotional tone.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Sadness): </b>Indicates a tendency to frequently show sadness in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Surprise): </b>Indicates a tendency to frequently show surprise in speech.": "./audio/sample.wav",
    }
  },
  {
    "Name": "Target Personality: Extraversion",
    "TestID": "Extraversion",
    "Text": "Please relate the personality <b>Extraversion</b> to conversation traits. You are required to answer whether each conversation trait (e.g. Frequent Laughter) is aligned with <b>Extraversion</b>.<br><br><b>Target Personality</b>: Extraversion<br><b>Explanation to 'Extraversion'</b>: talkative, assertive, energetic<br><b>Opposite Term</b>: 'Introversion'",
    "Files": {
      "<b>Frequent Taking Turns: </b>Indicates that the speaker often takes turns when there is an opportunity to speak.": "./audio/sample.wav",
      "<b>Long Talking Time per Turn: </b>Indicates that the speaker tends to talk for a long time before stopping or being interrupted.": "./audio/sample.wav",
      "<b>Frequent Laughter: </b>Indicates that laughter occurs often during the conversation (e.g., many laughs per minute).": "./audio/sample.wav",
      "<b>Frequent Emotive Backchannel: </b>Indicates that the speaker often provides emotional feedback (e.g., 'Wow!') while another person is talking.": "./audio/sample.wav",
      "<b>Frequent Cognitive Backchannel: </b>Indicates that the speaker often provides cognitive feedback (e.g., 'Oh, I see') while another person is talking.": "./audio/sample.wav",
      "<b>Frequent Interjections: </b>Indicates that there are many attempts to interrupt (both successful and unsuccessful interjections).": "./audio/sample.wav",
      "<b>Frequent Positive Sentiment: </b>Indicates a tendency to frequently use positive language.": "./audio/sample.wav",
      "<b>Frequent Neutral Sentiment: </b>Indicates a tendency to frequently use neutral language.": "./audio/sample.wav",
      "<b>Frequent Negative Sentiment: </b>Indicates a tendency to frequently use negative language.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Anger): </b>Indicates a tendency to frequently show anger in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Disgust): </b>Indicates a tendency to frequently show disgust in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Fear): </b>Indicates a tendency to frequently show fear in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Joy): </b>Indicates a tendency to frequently show joy in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Neutral): </b>Indicates a tendency to frequently remain neutral in emotional tone.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Sadness): </b>Indicates a tendency to frequently show sadness in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Surprise): </b>Indicates a tendency to frequently show surprise in speech.": "./audio/sample.wav",
    }
  },
  {
    "Name": "Target Personality: Agreeableness",
    "TestID": "Agreeableness",
    "Text": "Please relate the personality <b>Agreeableness</b> to conversation traits. You are required to answer whether each conversation trait (e.g. Frequent Laughter) is aligned with <b>Agreeableness</b>.<br><br><b>Target Personality</b>: Agreeableness<br><b>Explanation to 'Agreeableness'</b>: good-natured, cooperative, trustful<br><b>Opposite Term</b>: 'Antagonism'",
    "Files": {
      "<b>Frequent Taking Turns: </b>Indicates that the speaker often takes turns when there is an opportunity to speak.": "./audio/sample.wav",
      "<b>Long Talking Time per Turn: </b>Indicates that the speaker tends to talk for a long time before stopping or being interrupted.": "./audio/sample.wav",
      "<b>Frequent Laughter: </b>Indicates that laughter occurs often during the conversation (e.g., many laughs per minute).": "./audio/sample.wav",
      "<b>Frequent Emotive Backchannel: </b>Indicates that the speaker often provides emotional feedback (e.g., 'Wow!') while another person is talking.": "./audio/sample.wav",
      "<b>Frequent Cognitive Backchannel: </b>Indicates that the speaker often provides cognitive feedback (e.g., 'Oh, I see') while another person is talking.": "./audio/sample.wav",
      "<b>Frequent Interjections: </b>Indicates that there are many attempts to interrupt (both successful and unsuccessful interjections).": "./audio/sample.wav",
      "<b>Frequent Positive Sentiment: </b>Indicates a tendency to frequently use positive language.": "./audio/sample.wav",
      "<b>Frequent Neutral Sentiment: </b>Indicates a tendency to frequently use neutral language.": "./audio/sample.wav",
      "<b>Frequent Negative Sentiment: </b>Indicates a tendency to frequently use negative language.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Anger): </b>Indicates a tendency to frequently show anger in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Disgust): </b>Indicates a tendency to frequently show disgust in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Fear): </b>Indicates a tendency to frequently show fear in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Joy): </b>Indicates a tendency to frequently show joy in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Neutral): </b>Indicates a tendency to frequently remain neutral in emotional tone.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Sadness): </b>Indicates a tendency to frequently show sadness in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Surprise): </b>Indicates a tendency to frequently show surprise in speech.": "./audio/sample.wav",
    }
  },
  {
    "Name": "Target Personality: Neuroticism",
    "TestID": "Neuroticism",
    "Text": "Please relate the personality <b>Neuroticism</b> to conversation traits. You are required to answer whether each conversation trait (e.g. Frequent Laughter) is aligned with <b>Neuroticism</b>.<br><br><b>Target Personality</b>: Neuroticism<br><b>Explanation to 'Neuroticism'</b>: emotional instability, irritability, anxiety, self-doubt, depression<br><b>Opposite Term</b>: 'Emotion stability'",
    "Files": {
      "<b>Frequent Taking Turns: </b>Indicates that the speaker often takes turns when there is an opportunity to speak.": "./audio/sample.wav",
      "<b>Long Talking Time per Turn: </b>Indicates that the speaker tends to talk for a long time before stopping or being interrupted.": "./audio/sample.wav",
      "<b>Frequent Laughter: </b>Indicates that laughter occurs often during the conversation (e.g., many laughs per minute).": "./audio/sample.wav",
      "<b>Frequent Emotive Backchannel: </b>Indicates that the speaker often provides emotional feedback (e.g., 'Wow!') while another person is talking.": "./audio/sample.wav",
      "<b>Frequent Cognitive Backchannel: </b>Indicates that the speaker often provides cognitive feedback (e.g., 'Oh, I see') while another person is talking.": "./audio/sample.wav",
      "<b>Frequent Interjections: </b>Indicates that there are many attempts to interrupt (both successful and unsuccessful interjections).": "./audio/sample.wav",
      "<b>Frequent Positive Sentiment: </b>Indicates a tendency to frequently use positive language.": "./audio/sample.wav",
      "<b>Frequent Neutral Sentiment: </b>Indicates a tendency to frequently use neutral language.": "./audio/sample.wav",
      "<b>Frequent Negative Sentiment: </b>Indicates a tendency to frequently use negative language.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Anger): </b>Indicates a tendency to frequently show anger in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Disgust): </b>Indicates a tendency to frequently show disgust in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Fear): </b>Indicates a tendency to frequently show fear in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Joy): </b>Indicates a tendency to frequently show joy in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Neutral): </b>Indicates a tendency to frequently remain neutral in emotional tone.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Sadness): </b>Indicates a tendency to frequently show sadness in speech.": "./audio/sample.wav",
      "<b>Frequent Emotional Statement (Surprise): </b>Indicates a tendency to frequently show surprise in speech.": "./audio/sample.wav",
    }
  },
]
}