var TestConfig = {
  "TestName": "Personality Labeling Survey",
  "RateScalePng": "img/alignment.png",
  "RateScaleBgPng": "img/scale_abs_background.png",
  "RateMinValue": 0,
  "RateMaxValue": 100,
  "RateDefaultValue":0,
  "ShowFileIDs": false,
  "ShowResults": false,
  "LoopByDefault": false,
  "EnableABLoop": true,
  "EnableOnlineSubmission": false,
  "BeaqleServiceURL": "/web_service/beaqleJS_Service.php",
  "SupervisorContact": "shoinoue@link.cuhk.edu.cn",
  "RandomizeTestOrder": true,
  "MaxTestsPerRun": 10000,
  "RequireMaxRating": false,
  "AudioRoot": "",
  "Testsets":
[
      {
        "Name": "fe_03_00006",
        "TestID": "19___fe_03_00006",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00006/stereo.wav",
      "Mono": "./audio/9/fe_03_00006/mono.wav",
      "Left": "./audio/9/fe_03_00006/0.wav",
      "Right": "./audio/9/fe_03_00006/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00010",
        "TestID": "19___fe_03_00010",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00010/stereo.wav",
      "Mono": "./audio/9/fe_03_00010/mono.wav",
      "Left": "./audio/9/fe_03_00010/0.wav",
      "Right": "./audio/9/fe_03_00010/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00011",
        "TestID": "19___fe_03_00011",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00011/stereo.wav",
      "Mono": "./audio/9/fe_03_00011/mono.wav",
      "Left": "./audio/9/fe_03_00011/0.wav",
      "Right": "./audio/9/fe_03_00011/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00014",
        "TestID": "19___fe_03_00014",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00014/stereo.wav",
      "Mono": "./audio/9/fe_03_00014/mono.wav",
      "Left": "./audio/9/fe_03_00014/0.wav",
      "Right": "./audio/9/fe_03_00014/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00016",
        "TestID": "19___fe_03_00016",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00016/stereo.wav",
      "Mono": "./audio/9/fe_03_00016/mono.wav",
      "Left": "./audio/9/fe_03_00016/0.wav",
      "Right": "./audio/9/fe_03_00016/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00017",
        "TestID": "19___fe_03_00017",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00017/stereo.wav",
      "Mono": "./audio/9/fe_03_00017/mono.wav",
      "Left": "./audio/9/fe_03_00017/0.wav",
      "Right": "./audio/9/fe_03_00017/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00021",
        "TestID": "19___fe_03_00021",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00021/stereo.wav",
      "Mono": "./audio/9/fe_03_00021/mono.wav",
      "Left": "./audio/9/fe_03_00021/0.wav",
      "Right": "./audio/9/fe_03_00021/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00023",
        "TestID": "19___fe_03_00023",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00023/stereo.wav",
      "Mono": "./audio/9/fe_03_00023/mono.wav",
      "Left": "./audio/9/fe_03_00023/0.wav",
      "Right": "./audio/9/fe_03_00023/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00025",
        "TestID": "19___fe_03_00025",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00025/stereo.wav",
      "Mono": "./audio/9/fe_03_00025/mono.wav",
      "Left": "./audio/9/fe_03_00025/0.wav",
      "Right": "./audio/9/fe_03_00025/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00030",
        "TestID": "19___fe_03_00030",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00030/stereo.wav",
      "Mono": "./audio/9/fe_03_00030/mono.wav",
      "Left": "./audio/9/fe_03_00030/0.wav",
      "Right": "./audio/9/fe_03_00030/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00033",
        "TestID": "19___fe_03_00033",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00033/stereo.wav",
      "Mono": "./audio/9/fe_03_00033/mono.wav",
      "Left": "./audio/9/fe_03_00033/0.wav",
      "Right": "./audio/9/fe_03_00033/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00042",
        "TestID": "19___fe_03_00042",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00042/stereo.wav",
      "Mono": "./audio/9/fe_03_00042/mono.wav",
      "Left": "./audio/9/fe_03_00042/0.wav",
      "Right": "./audio/9/fe_03_00042/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00055",
        "TestID": "19___fe_03_00055",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00055/stereo.wav",
      "Mono": "./audio/9/fe_03_00055/mono.wav",
      "Left": "./audio/9/fe_03_00055/0.wav",
      "Right": "./audio/9/fe_03_00055/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00069",
        "TestID": "19___fe_03_00069",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00069/stereo.wav",
      "Mono": "./audio/9/fe_03_00069/mono.wav",
      "Left": "./audio/9/fe_03_00069/0.wav",
      "Right": "./audio/9/fe_03_00069/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00076",
        "TestID": "19___fe_03_00076",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00076/stereo.wav",
      "Mono": "./audio/9/fe_03_00076/mono.wav",
      "Left": "./audio/9/fe_03_00076/0.wav",
      "Right": "./audio/9/fe_03_00076/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00077",
        "TestID": "19___fe_03_00077",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00077/stereo.wav",
      "Mono": "./audio/9/fe_03_00077/mono.wav",
      "Left": "./audio/9/fe_03_00077/0.wav",
      "Right": "./audio/9/fe_03_00077/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00080",
        "TestID": "19___fe_03_00080",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00080/stereo.wav",
      "Mono": "./audio/9/fe_03_00080/mono.wav",
      "Left": "./audio/9/fe_03_00080/0.wav",
      "Right": "./audio/9/fe_03_00080/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00081",
        "TestID": "19___fe_03_00081",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00081/stereo.wav",
      "Mono": "./audio/9/fe_03_00081/mono.wav",
      "Left": "./audio/9/fe_03_00081/0.wav",
      "Right": "./audio/9/fe_03_00081/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00084",
        "TestID": "19___fe_03_00084",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/9/fe_03_00084/stereo.wav",
      "Mono": "./audio/9/fe_03_00084/mono.wav",
      "Left": "./audio/9/fe_03_00084/0.wav",
      "Right": "./audio/9/fe_03_00084/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
]
}