var TestConfig = {
  "TestName": "Personality Labeling Survey",
  "RateScalePng": "img/alignment.png",
  "RateScaleBgPng": "img/scale_abs_background.png",
  "RateMinValue": 0,
  "RateMaxValue": 100,
  "RateDefaultValue":50,
  "ShowFileIDs": false,
  "ShowResults": false,
  "LoopByDefault": false,
  "EnableABLoop": true,
  "EnableOnlineSubmission": false,
  "BeaqleServiceURL": "/web_service/beaqleJS_Service.php",
  "SupervisorContact": "shoinoue@link.cuhk.edu.cn",
  "RandomizeTestOrder": true,
  "MaxTestsPerRun": 10000,
  "RequireMaxRating": false,
  "AudioRoot": "",
  "Testsets":
[
      {
        "Name": "fe_03_00009",
        "TestID": "16___fe_03_00009",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00009/stereo.wav",
      "Mono": "./audio/16/fe_03_00009/mono.wav",
      "Left": "./audio/16/fe_03_00009/0.wav",
      "Right": "./audio/16/fe_03_00009/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00010",
        "TestID": "16___fe_03_00010",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00010/stereo.wav",
      "Mono": "./audio/16/fe_03_00010/mono.wav",
      "Left": "./audio/16/fe_03_00010/0.wav",
      "Right": "./audio/16/fe_03_00010/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00013",
        "TestID": "16___fe_03_00013",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00013/stereo.wav",
      "Mono": "./audio/16/fe_03_00013/mono.wav",
      "Left": "./audio/16/fe_03_00013/0.wav",
      "Right": "./audio/16/fe_03_00013/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00016",
        "TestID": "16___fe_03_00016",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00016/stereo.wav",
      "Mono": "./audio/16/fe_03_00016/mono.wav",
      "Left": "./audio/16/fe_03_00016/0.wav",
      "Right": "./audio/16/fe_03_00016/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00017",
        "TestID": "16___fe_03_00017",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00017/stereo.wav",
      "Mono": "./audio/16/fe_03_00017/mono.wav",
      "Left": "./audio/16/fe_03_00017/0.wav",
      "Right": "./audio/16/fe_03_00017/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00018",
        "TestID": "16___fe_03_00018",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00018/stereo.wav",
      "Mono": "./audio/16/fe_03_00018/mono.wav",
      "Left": "./audio/16/fe_03_00018/0.wav",
      "Right": "./audio/16/fe_03_00018/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00022",
        "TestID": "16___fe_03_00022",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00022/stereo.wav",
      "Mono": "./audio/16/fe_03_00022/mono.wav",
      "Left": "./audio/16/fe_03_00022/0.wav",
      "Right": "./audio/16/fe_03_00022/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00036",
        "TestID": "16___fe_03_00036",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00036/stereo.wav",
      "Mono": "./audio/16/fe_03_00036/mono.wav",
      "Left": "./audio/16/fe_03_00036/0.wav",
      "Right": "./audio/16/fe_03_00036/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00037",
        "TestID": "16___fe_03_00037",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00037/stereo.wav",
      "Mono": "./audio/16/fe_03_00037/mono.wav",
      "Left": "./audio/16/fe_03_00037/0.wav",
      "Right": "./audio/16/fe_03_00037/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00039",
        "TestID": "16___fe_03_00039",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00039/stereo.wav",
      "Mono": "./audio/16/fe_03_00039/mono.wav",
      "Left": "./audio/16/fe_03_00039/0.wav",
      "Right": "./audio/16/fe_03_00039/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00045",
        "TestID": "16___fe_03_00045",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00045/stereo.wav",
      "Mono": "./audio/16/fe_03_00045/mono.wav",
      "Left": "./audio/16/fe_03_00045/0.wav",
      "Right": "./audio/16/fe_03_00045/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00051",
        "TestID": "16___fe_03_00051",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00051/stereo.wav",
      "Mono": "./audio/16/fe_03_00051/mono.wav",
      "Left": "./audio/16/fe_03_00051/0.wav",
      "Right": "./audio/16/fe_03_00051/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00055",
        "TestID": "16___fe_03_00055",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00055/stereo.wav",
      "Mono": "./audio/16/fe_03_00055/mono.wav",
      "Left": "./audio/16/fe_03_00055/0.wav",
      "Right": "./audio/16/fe_03_00055/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00058",
        "TestID": "16___fe_03_00058",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00058/stereo.wav",
      "Mono": "./audio/16/fe_03_00058/mono.wav",
      "Left": "./audio/16/fe_03_00058/0.wav",
      "Right": "./audio/16/fe_03_00058/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00062",
        "TestID": "16___fe_03_00062",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00062/stereo.wav",
      "Mono": "./audio/16/fe_03_00062/mono.wav",
      "Left": "./audio/16/fe_03_00062/0.wav",
      "Right": "./audio/16/fe_03_00062/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00080",
        "TestID": "16___fe_03_00080",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00080/stereo.wav",
      "Mono": "./audio/16/fe_03_00080/mono.wav",
      "Left": "./audio/16/fe_03_00080/0.wav",
      "Right": "./audio/16/fe_03_00080/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00086",
        "TestID": "16___fe_03_00086",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00086/stereo.wav",
      "Mono": "./audio/16/fe_03_00086/mono.wav",
      "Left": "./audio/16/fe_03_00086/0.wav",
      "Right": "./audio/16/fe_03_00086/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00088",
        "TestID": "16___fe_03_00088",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00088/stereo.wav",
      "Mono": "./audio/16/fe_03_00088/mono.wav",
      "Left": "./audio/16/fe_03_00088/0.wav",
      "Right": "./audio/16/fe_03_00088/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00092",
        "TestID": "16___fe_03_00092",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/16/fe_03_00092/stereo.wav",
      "Mono": "./audio/16/fe_03_00092/mono.wav",
      "Left": "./audio/16/fe_03_00092/0.wav",
      "Right": "./audio/16/fe_03_00092/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
]
}