var TestConfig = {
  "TestName": "Personality Labeling Survey",
  "RateScalePng": "img/alignment.png",
  "RateScaleBgPng": "img/scale_abs_background.png",
  "RateMinValue": 0,
  "RateMaxValue": 100,
  "RateDefaultValue":50,
  "ShowFileIDs": false,
  "ShowResults": false,
  "LoopByDefault": false,
  "EnableABLoop": true,
  "EnableOnlineSubmission": false,
  "BeaqleServiceURL": "/web_service/beaqleJS_Service.php",
  "SupervisorContact": "shoinoue@link.cuhk.edu.cn",
  "RandomizeTestOrder": true,
  "MaxTestsPerRun": 10000,
  "RequireMaxRating": false,
  "AudioRoot": "",
  "Testsets":
[
          {
            "Name": "fe_03_00021",
            "TestID": "0___fe_03_00021",
            "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
            "Files": {
      "Stereo": "./audio/0/fe_03_00021/stereo.wav",
      "Mono": "./audio/0/fe_03_00021/mono.wav",
      "Left": "./audio/0/fe_03_00021/0.wav",
      "Right": "./audio/0/fe_03_00021/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
    }
  },
          {
            "Name": "fe_03_00027",
            "TestID": "0___fe_03_00027",
            "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
            "Files": {
      "Stereo": "./audio/0/fe_03_00027/stereo.wav",
      "Mono": "./audio/0/fe_03_00027/mono.wav",
      "Left": "./audio/0/fe_03_00027/0.wav",
      "Right": "./audio/0/fe_03_00027/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
    }
  },
          {
            "Name": "fe_03_00035",
            "TestID": "0___fe_03_00035",
            "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
            "Files": {
      "Stereo": "./audio/0/fe_03_00035/stereo.wav",
      "Mono": "./audio/0/fe_03_00035/mono.wav",
      "Left": "./audio/0/fe_03_00035/0.wav",
      "Right": "./audio/0/fe_03_00035/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
    }
  },
          {
            "Name": "fe_03_00038",
            "TestID": "0___fe_03_00038",
            "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
            "Files": {
      "Stereo": "./audio/0/fe_03_00038/stereo.wav",
      "Mono": "./audio/0/fe_03_00038/mono.wav",
      "Left": "./audio/0/fe_03_00038/0.wav",
      "Right": "./audio/0/fe_03_00038/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/samples/sample1.wav",
    }
  },
]
}