var TestConfig = {
  "TestName": "Personality Labeling Survey",
  "RateScalePng": "img/alignment.png",
  "RateScaleBgPng": "img/scale_abs_background.png",
  "RateMinValue": 0,
  "RateMaxValue": 100,
  "RateDefaultValue":0,
  "ShowFileIDs": false,
  "ShowResults": false,
  "LoopByDefault": false,
  "EnableABLoop": true,
  "EnableOnlineSubmission": false,
  "BeaqleServiceURL": "/web_service/beaqleJS_Service.php",
  "SupervisorContact": "shoinoue@link.cuhk.edu.cn",
  "RandomizeTestOrder": true,
  "MaxTestsPerRun": 10000,
  "RequireMaxRating": false,
  "AudioRoot": "",
  "Testsets":
[
      {
        "Name": "fe_03_00014",
        "TestID": "4___fe_03_00014",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00014/stereo.wav",
      "Mono": "./audio/12/fe_03_00014/mono.wav",
      "Left": "./audio/12/fe_03_00014/0.wav",
      "Right": "./audio/12/fe_03_00014/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00015",
        "TestID": "4___fe_03_00015",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00015/stereo.wav",
      "Mono": "./audio/12/fe_03_00015/mono.wav",
      "Left": "./audio/12/fe_03_00015/0.wav",
      "Right": "./audio/12/fe_03_00015/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00017",
        "TestID": "4___fe_03_00017",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00017/stereo.wav",
      "Mono": "./audio/12/fe_03_00017/mono.wav",
      "Left": "./audio/12/fe_03_00017/0.wav",
      "Right": "./audio/12/fe_03_00017/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00022",
        "TestID": "4___fe_03_00022",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00022/stereo.wav",
      "Mono": "./audio/12/fe_03_00022/mono.wav",
      "Left": "./audio/12/fe_03_00022/0.wav",
      "Right": "./audio/12/fe_03_00022/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00024",
        "TestID": "4___fe_03_00024",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00024/stereo.wav",
      "Mono": "./audio/12/fe_03_00024/mono.wav",
      "Left": "./audio/12/fe_03_00024/0.wav",
      "Right": "./audio/12/fe_03_00024/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00037",
        "TestID": "4___fe_03_00037",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00037/stereo.wav",
      "Mono": "./audio/12/fe_03_00037/mono.wav",
      "Left": "./audio/12/fe_03_00037/0.wav",
      "Right": "./audio/12/fe_03_00037/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00046",
        "TestID": "4___fe_03_00046",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00046/stereo.wav",
      "Mono": "./audio/12/fe_03_00046/mono.wav",
      "Left": "./audio/12/fe_03_00046/0.wav",
      "Right": "./audio/12/fe_03_00046/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00050",
        "TestID": "4___fe_03_00050",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00050/stereo.wav",
      "Mono": "./audio/12/fe_03_00050/mono.wav",
      "Left": "./audio/12/fe_03_00050/0.wav",
      "Right": "./audio/12/fe_03_00050/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00058",
        "TestID": "4___fe_03_00058",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00058/stereo.wav",
      "Mono": "./audio/12/fe_03_00058/mono.wav",
      "Left": "./audio/12/fe_03_00058/0.wav",
      "Right": "./audio/12/fe_03_00058/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00060",
        "TestID": "4___fe_03_00060",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00060/stereo.wav",
      "Mono": "./audio/12/fe_03_00060/mono.wav",
      "Left": "./audio/12/fe_03_00060/0.wav",
      "Right": "./audio/12/fe_03_00060/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00062",
        "TestID": "4___fe_03_00062",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00062/stereo.wav",
      "Mono": "./audio/12/fe_03_00062/mono.wav",
      "Left": "./audio/12/fe_03_00062/0.wav",
      "Right": "./audio/12/fe_03_00062/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00066",
        "TestID": "4___fe_03_00066",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00066/stereo.wav",
      "Mono": "./audio/12/fe_03_00066/mono.wav",
      "Left": "./audio/12/fe_03_00066/0.wav",
      "Right": "./audio/12/fe_03_00066/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00067",
        "TestID": "4___fe_03_00067",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00067/stereo.wav",
      "Mono": "./audio/12/fe_03_00067/mono.wav",
      "Left": "./audio/12/fe_03_00067/0.wav",
      "Right": "./audio/12/fe_03_00067/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00069",
        "TestID": "4___fe_03_00069",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00069/stereo.wav",
      "Mono": "./audio/12/fe_03_00069/mono.wav",
      "Left": "./audio/12/fe_03_00069/0.wav",
      "Right": "./audio/12/fe_03_00069/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00070",
        "TestID": "4___fe_03_00070",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00070/stereo.wav",
      "Mono": "./audio/12/fe_03_00070/mono.wav",
      "Left": "./audio/12/fe_03_00070/0.wav",
      "Right": "./audio/12/fe_03_00070/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00076",
        "TestID": "4___fe_03_00076",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00076/stereo.wav",
      "Mono": "./audio/12/fe_03_00076/mono.wav",
      "Left": "./audio/12/fe_03_00076/0.wav",
      "Right": "./audio/12/fe_03_00076/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00079",
        "TestID": "4___fe_03_00079",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00079/stereo.wav",
      "Mono": "./audio/12/fe_03_00079/mono.wav",
      "Left": "./audio/12/fe_03_00079/0.wav",
      "Right": "./audio/12/fe_03_00079/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00095",
        "TestID": "4___fe_03_00095",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00095/stereo.wav",
      "Mono": "./audio/12/fe_03_00095/mono.wav",
      "Left": "./audio/12/fe_03_00095/0.wav",
      "Right": "./audio/12/fe_03_00095/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00096",
        "TestID": "4___fe_03_00096",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/12/fe_03_00096/stereo.wav",
      "Mono": "./audio/12/fe_03_00096/mono.wav",
      "Left": "./audio/12/fe_03_00096/0.wav",
      "Right": "./audio/12/fe_03_00096/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
]
}