var TestConfig = {
  "TestName": "Personality Labeling Survey",
  "RateScalePng": "img/alignment.png",
  "RateScaleBgPng": "img/scale_abs_background.png",
  "RateMinValue": 0,
  "RateMaxValue": 100,
  "RateDefaultValue":50,
  "ShowFileIDs": false,
  "ShowResults": false,
  "LoopByDefault": false,
  "EnableABLoop": true,
  "EnableOnlineSubmission": false,
  "BeaqleServiceURL": "/web_service/beaqleJS_Service.php",
  "SupervisorContact": "shoinoue@link.cuhk.edu.cn",
  "RandomizeTestOrder": true,
  "MaxTestsPerRun": 10000,
  "RequireMaxRating": false,
  "AudioRoot": "",
  "Testsets":
[
      {
        "Name": "fe_03_00006",
        "TestID": "18___fe_03_00006",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00006/stereo.wav",
      "Mono": "./audio/18/fe_03_00006/mono.wav",
      "Left": "./audio/18/fe_03_00006/0.wav",
      "Right": "./audio/18/fe_03_00006/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00007",
        "TestID": "18___fe_03_00007",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00007/stereo.wav",
      "Mono": "./audio/18/fe_03_00007/mono.wav",
      "Left": "./audio/18/fe_03_00007/0.wav",
      "Right": "./audio/18/fe_03_00007/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00012",
        "TestID": "18___fe_03_00012",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00012/stereo.wav",
      "Mono": "./audio/18/fe_03_00012/mono.wav",
      "Left": "./audio/18/fe_03_00012/0.wav",
      "Right": "./audio/18/fe_03_00012/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00020",
        "TestID": "18___fe_03_00020",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00020/stereo.wav",
      "Mono": "./audio/18/fe_03_00020/mono.wav",
      "Left": "./audio/18/fe_03_00020/0.wav",
      "Right": "./audio/18/fe_03_00020/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00034",
        "TestID": "18___fe_03_00034",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00034/stereo.wav",
      "Mono": "./audio/18/fe_03_00034/mono.wav",
      "Left": "./audio/18/fe_03_00034/0.wav",
      "Right": "./audio/18/fe_03_00034/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00035",
        "TestID": "18___fe_03_00035",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00035/stereo.wav",
      "Mono": "./audio/18/fe_03_00035/mono.wav",
      "Left": "./audio/18/fe_03_00035/0.wav",
      "Right": "./audio/18/fe_03_00035/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00038",
        "TestID": "18___fe_03_00038",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00038/stereo.wav",
      "Mono": "./audio/18/fe_03_00038/mono.wav",
      "Left": "./audio/18/fe_03_00038/0.wav",
      "Right": "./audio/18/fe_03_00038/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00042",
        "TestID": "18___fe_03_00042",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00042/stereo.wav",
      "Mono": "./audio/18/fe_03_00042/mono.wav",
      "Left": "./audio/18/fe_03_00042/0.wav",
      "Right": "./audio/18/fe_03_00042/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00048",
        "TestID": "18___fe_03_00048",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00048/stereo.wav",
      "Mono": "./audio/18/fe_03_00048/mono.wav",
      "Left": "./audio/18/fe_03_00048/0.wav",
      "Right": "./audio/18/fe_03_00048/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00053",
        "TestID": "18___fe_03_00053",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00053/stereo.wav",
      "Mono": "./audio/18/fe_03_00053/mono.wav",
      "Left": "./audio/18/fe_03_00053/0.wav",
      "Right": "./audio/18/fe_03_00053/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00054",
        "TestID": "18___fe_03_00054",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00054/stereo.wav",
      "Mono": "./audio/18/fe_03_00054/mono.wav",
      "Left": "./audio/18/fe_03_00054/0.wav",
      "Right": "./audio/18/fe_03_00054/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00056",
        "TestID": "18___fe_03_00056",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00056/stereo.wav",
      "Mono": "./audio/18/fe_03_00056/mono.wav",
      "Left": "./audio/18/fe_03_00056/0.wav",
      "Right": "./audio/18/fe_03_00056/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00064",
        "TestID": "18___fe_03_00064",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00064/stereo.wav",
      "Mono": "./audio/18/fe_03_00064/mono.wav",
      "Left": "./audio/18/fe_03_00064/0.wav",
      "Right": "./audio/18/fe_03_00064/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00065",
        "TestID": "18___fe_03_00065",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00065/stereo.wav",
      "Mono": "./audio/18/fe_03_00065/mono.wav",
      "Left": "./audio/18/fe_03_00065/0.wav",
      "Right": "./audio/18/fe_03_00065/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00067",
        "TestID": "18___fe_03_00067",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00067/stereo.wav",
      "Mono": "./audio/18/fe_03_00067/mono.wav",
      "Left": "./audio/18/fe_03_00067/0.wav",
      "Right": "./audio/18/fe_03_00067/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00068",
        "TestID": "18___fe_03_00068",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00068/stereo.wav",
      "Mono": "./audio/18/fe_03_00068/mono.wav",
      "Left": "./audio/18/fe_03_00068/0.wav",
      "Right": "./audio/18/fe_03_00068/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00074",
        "TestID": "18___fe_03_00074",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00074/stereo.wav",
      "Mono": "./audio/18/fe_03_00074/mono.wav",
      "Left": "./audio/18/fe_03_00074/0.wav",
      "Right": "./audio/18/fe_03_00074/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00087",
        "TestID": "18___fe_03_00087",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00087/stereo.wav",
      "Mono": "./audio/18/fe_03_00087/mono.wav",
      "Left": "./audio/18/fe_03_00087/0.wav",
      "Right": "./audio/18/fe_03_00087/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00099",
        "TestID": "18___fe_03_00099",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/18/fe_03_00099/stereo.wav",
      "Mono": "./audio/18/fe_03_00099/mono.wav",
      "Left": "./audio/18/fe_03_00099/0.wav",
      "Right": "./audio/18/fe_03_00099/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
]
}