var TestConfig = {
  "TestName": "Personality Labeling Survey",
  "RateScalePng": "img/alignment.png",
  "RateScaleBgPng": "img/scale_abs_background.png",
  "RateMinValue": 0,
  "RateMaxValue": 100,
  "RateDefaultValue":50,
  "ShowFileIDs": false,
  "ShowResults": false,
  "LoopByDefault": false,
  "EnableABLoop": true,
  "EnableOnlineSubmission": false,
  "BeaqleServiceURL": "/web_service/beaqleJS_Service.php",
  "SupervisorContact": "shoinoue@link.cuhk.edu.cn",
  "RandomizeTestOrder": true,
  "MaxTestsPerRun": 10000,
  "RequireMaxRating": false,
  "AudioRoot": "",
  "Testsets":
[
      {
        "Name": "fe_03_00011",
        "TestID": "15___fe_03_00011",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00011/stereo.wav",
      "Mono": "./audio/15/fe_03_00011/mono.wav",
      "Left": "./audio/15/fe_03_00011/0.wav",
      "Right": "./audio/15/fe_03_00011/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00014",
        "TestID": "15___fe_03_00014",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00014/stereo.wav",
      "Mono": "./audio/15/fe_03_00014/mono.wav",
      "Left": "./audio/15/fe_03_00014/0.wav",
      "Right": "./audio/15/fe_03_00014/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00028",
        "TestID": "15___fe_03_00028",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00028/stereo.wav",
      "Mono": "./audio/15/fe_03_00028/mono.wav",
      "Left": "./audio/15/fe_03_00028/0.wav",
      "Right": "./audio/15/fe_03_00028/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00030",
        "TestID": "15___fe_03_00030",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00030/stereo.wav",
      "Mono": "./audio/15/fe_03_00030/mono.wav",
      "Left": "./audio/15/fe_03_00030/0.wav",
      "Right": "./audio/15/fe_03_00030/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00047",
        "TestID": "15___fe_03_00047",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00047/stereo.wav",
      "Mono": "./audio/15/fe_03_00047/mono.wav",
      "Left": "./audio/15/fe_03_00047/0.wav",
      "Right": "./audio/15/fe_03_00047/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00050",
        "TestID": "15___fe_03_00050",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00050/stereo.wav",
      "Mono": "./audio/15/fe_03_00050/mono.wav",
      "Left": "./audio/15/fe_03_00050/0.wav",
      "Right": "./audio/15/fe_03_00050/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00052",
        "TestID": "15___fe_03_00052",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00052/stereo.wav",
      "Mono": "./audio/15/fe_03_00052/mono.wav",
      "Left": "./audio/15/fe_03_00052/0.wav",
      "Right": "./audio/15/fe_03_00052/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00060",
        "TestID": "15___fe_03_00060",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00060/stereo.wav",
      "Mono": "./audio/15/fe_03_00060/mono.wav",
      "Left": "./audio/15/fe_03_00060/0.wav",
      "Right": "./audio/15/fe_03_00060/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00063",
        "TestID": "15___fe_03_00063",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00063/stereo.wav",
      "Mono": "./audio/15/fe_03_00063/mono.wav",
      "Left": "./audio/15/fe_03_00063/0.wav",
      "Right": "./audio/15/fe_03_00063/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00070",
        "TestID": "15___fe_03_00070",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00070/stereo.wav",
      "Mono": "./audio/15/fe_03_00070/mono.wav",
      "Left": "./audio/15/fe_03_00070/0.wav",
      "Right": "./audio/15/fe_03_00070/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00072",
        "TestID": "15___fe_03_00072",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00072/stereo.wav",
      "Mono": "./audio/15/fe_03_00072/mono.wav",
      "Left": "./audio/15/fe_03_00072/0.wav",
      "Right": "./audio/15/fe_03_00072/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00073",
        "TestID": "15___fe_03_00073",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00073/stereo.wav",
      "Mono": "./audio/15/fe_03_00073/mono.wav",
      "Left": "./audio/15/fe_03_00073/0.wav",
      "Right": "./audio/15/fe_03_00073/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00075",
        "TestID": "15___fe_03_00075",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00075/stereo.wav",
      "Mono": "./audio/15/fe_03_00075/mono.wav",
      "Left": "./audio/15/fe_03_00075/0.wav",
      "Right": "./audio/15/fe_03_00075/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00076",
        "TestID": "15___fe_03_00076",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00076/stereo.wav",
      "Mono": "./audio/15/fe_03_00076/mono.wav",
      "Left": "./audio/15/fe_03_00076/0.wav",
      "Right": "./audio/15/fe_03_00076/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00082",
        "TestID": "15___fe_03_00082",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00082/stereo.wav",
      "Mono": "./audio/15/fe_03_00082/mono.wav",
      "Left": "./audio/15/fe_03_00082/0.wav",
      "Right": "./audio/15/fe_03_00082/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00083",
        "TestID": "15___fe_03_00083",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00083/stereo.wav",
      "Mono": "./audio/15/fe_03_00083/mono.wav",
      "Left": "./audio/15/fe_03_00083/0.wav",
      "Right": "./audio/15/fe_03_00083/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00085",
        "TestID": "15___fe_03_00085",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00085/stereo.wav",
      "Mono": "./audio/15/fe_03_00085/mono.wav",
      "Left": "./audio/15/fe_03_00085/0.wav",
      "Right": "./audio/15/fe_03_00085/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00093",
        "TestID": "15___fe_03_00093",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00093/stereo.wav",
      "Mono": "./audio/15/fe_03_00093/mono.wav",
      "Left": "./audio/15/fe_03_00093/0.wav",
      "Right": "./audio/15/fe_03_00093/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00098",
        "TestID": "15___fe_03_00098",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/15/fe_03_00098/stereo.wav",
      "Mono": "./audio/15/fe_03_00098/mono.wav",
      "Left": "./audio/15/fe_03_00098/0.wav",
      "Right": "./audio/15/fe_03_00098/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
]
}