var TestConfig = {
  "TestName": "Personality Labeling Survey",
  "RateScalePng": "img/alignment.png",
  "RateScaleBgPng": "img/scale_abs_background.png",
  "RateMinValue": 0,
  "RateMaxValue": 100,
  "RateDefaultValue":50,
  "ShowFileIDs": false,
  "ShowResults": false,
  "LoopByDefault": false,
  "EnableABLoop": true,
  "EnableOnlineSubmission": false,
  "BeaqleServiceURL": "/web_service/beaqleJS_Service.php",
  "SupervisorContact": "shoinoue@link.cuhk.edu.cn",
  "RandomizeTestOrder": true,
  "MaxTestsPerRun": 10000,
  "RequireMaxRating": false,
  "AudioRoot": "",
  "Testsets":
[
      {
        "Name": "fe_03_00007",
        "TestID": "5___fe_03_00007",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00007/stereo.wav",
      "Mono": "./audio/5/fe_03_00007/mono.wav",
      "Left": "./audio/5/fe_03_00007/0.wav",
      "Right": "./audio/5/fe_03_00007/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00015",
        "TestID": "5___fe_03_00015",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00015/stereo.wav",
      "Mono": "./audio/5/fe_03_00015/mono.wav",
      "Left": "./audio/5/fe_03_00015/0.wav",
      "Right": "./audio/5/fe_03_00015/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00032",
        "TestID": "5___fe_03_00032",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00032/stereo.wav",
      "Mono": "./audio/5/fe_03_00032/mono.wav",
      "Left": "./audio/5/fe_03_00032/0.wav",
      "Right": "./audio/5/fe_03_00032/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00036",
        "TestID": "5___fe_03_00036",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00036/stereo.wav",
      "Mono": "./audio/5/fe_03_00036/mono.wav",
      "Left": "./audio/5/fe_03_00036/0.wav",
      "Right": "./audio/5/fe_03_00036/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00037",
        "TestID": "5___fe_03_00037",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00037/stereo.wav",
      "Mono": "./audio/5/fe_03_00037/mono.wav",
      "Left": "./audio/5/fe_03_00037/0.wav",
      "Right": "./audio/5/fe_03_00037/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00044",
        "TestID": "5___fe_03_00044",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00044/stereo.wav",
      "Mono": "./audio/5/fe_03_00044/mono.wav",
      "Left": "./audio/5/fe_03_00044/0.wav",
      "Right": "./audio/5/fe_03_00044/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00045",
        "TestID": "5___fe_03_00045",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00045/stereo.wav",
      "Mono": "./audio/5/fe_03_00045/mono.wav",
      "Left": "./audio/5/fe_03_00045/0.wav",
      "Right": "./audio/5/fe_03_00045/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00049",
        "TestID": "5___fe_03_00049",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00049/stereo.wav",
      "Mono": "./audio/5/fe_03_00049/mono.wav",
      "Left": "./audio/5/fe_03_00049/0.wav",
      "Right": "./audio/5/fe_03_00049/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00051",
        "TestID": "5___fe_03_00051",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00051/stereo.wav",
      "Mono": "./audio/5/fe_03_00051/mono.wav",
      "Left": "./audio/5/fe_03_00051/0.wav",
      "Right": "./audio/5/fe_03_00051/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00054",
        "TestID": "5___fe_03_00054",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00054/stereo.wav",
      "Mono": "./audio/5/fe_03_00054/mono.wav",
      "Left": "./audio/5/fe_03_00054/0.wav",
      "Right": "./audio/5/fe_03_00054/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00060",
        "TestID": "5___fe_03_00060",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00060/stereo.wav",
      "Mono": "./audio/5/fe_03_00060/mono.wav",
      "Left": "./audio/5/fe_03_00060/0.wav",
      "Right": "./audio/5/fe_03_00060/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00063",
        "TestID": "5___fe_03_00063",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00063/stereo.wav",
      "Mono": "./audio/5/fe_03_00063/mono.wav",
      "Left": "./audio/5/fe_03_00063/0.wav",
      "Right": "./audio/5/fe_03_00063/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00072",
        "TestID": "5___fe_03_00072",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00072/stereo.wav",
      "Mono": "./audio/5/fe_03_00072/mono.wav",
      "Left": "./audio/5/fe_03_00072/0.wav",
      "Right": "./audio/5/fe_03_00072/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00079",
        "TestID": "5___fe_03_00079",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00079/stereo.wav",
      "Mono": "./audio/5/fe_03_00079/mono.wav",
      "Left": "./audio/5/fe_03_00079/0.wav",
      "Right": "./audio/5/fe_03_00079/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00082",
        "TestID": "5___fe_03_00082",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00082/stereo.wav",
      "Mono": "./audio/5/fe_03_00082/mono.wav",
      "Left": "./audio/5/fe_03_00082/0.wav",
      "Right": "./audio/5/fe_03_00082/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00089",
        "TestID": "5___fe_03_00089",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00089/stereo.wav",
      "Mono": "./audio/5/fe_03_00089/mono.wav",
      "Left": "./audio/5/fe_03_00089/0.wav",
      "Right": "./audio/5/fe_03_00089/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00092",
        "TestID": "5___fe_03_00092",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00092/stereo.wav",
      "Mono": "./audio/5/fe_03_00092/mono.wav",
      "Left": "./audio/5/fe_03_00092/0.wav",
      "Right": "./audio/5/fe_03_00092/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00093",
        "TestID": "5___fe_03_00093",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00093/stereo.wav",
      "Mono": "./audio/5/fe_03_00093/mono.wav",
      "Left": "./audio/5/fe_03_00093/0.wav",
      "Right": "./audio/5/fe_03_00093/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00095",
        "TestID": "5___fe_03_00095",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/5/fe_03_00095/stereo.wav",
      "Mono": "./audio/5/fe_03_00095/mono.wav",
      "Left": "./audio/5/fe_03_00095/0.wav",
      "Right": "./audio/5/fe_03_00095/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
]
}