var TestConfig = {
  "TestName": "Personality Labeling Survey",
  "RateScalePng": "img/alignment.png",
  "RateScaleBgPng": "img/scale_abs_background.png",
  "RateMinValue": 0,
  "RateMaxValue": 100,
  "RateDefaultValue":50,
  "ShowFileIDs": false,
  "ShowResults": false,
  "LoopByDefault": false,
  "EnableABLoop": true,
  "EnableOnlineSubmission": false,
  "BeaqleServiceURL": "/web_service/beaqleJS_Service.php",
  "SupervisorContact": "shoinoue@link.cuhk.edu.cn",
  "RandomizeTestOrder": true,
  "MaxTestsPerRun": 10000,
  "RequireMaxRating": false,
  "AudioRoot": "",
  "Testsets":
[
      {
        "Name": "fe_03_00021",
        "TestID": "17___fe_03_00021",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00021/stereo.wav",
      "Mono": "./audio/17/fe_03_00021/mono.wav",
      "Left": "./audio/17/fe_03_00021/0.wav",
      "Right": "./audio/17/fe_03_00021/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00023",
        "TestID": "17___fe_03_00023",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00023/stereo.wav",
      "Mono": "./audio/17/fe_03_00023/mono.wav",
      "Left": "./audio/17/fe_03_00023/0.wav",
      "Right": "./audio/17/fe_03_00023/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00032",
        "TestID": "17___fe_03_00032",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00032/stereo.wav",
      "Mono": "./audio/17/fe_03_00032/mono.wav",
      "Left": "./audio/17/fe_03_00032/0.wav",
      "Right": "./audio/17/fe_03_00032/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00033",
        "TestID": "17___fe_03_00033",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00033/stereo.wav",
      "Mono": "./audio/17/fe_03_00033/mono.wav",
      "Left": "./audio/17/fe_03_00033/0.wav",
      "Right": "./audio/17/fe_03_00033/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00040",
        "TestID": "17___fe_03_00040",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00040/stereo.wav",
      "Mono": "./audio/17/fe_03_00040/mono.wav",
      "Left": "./audio/17/fe_03_00040/0.wav",
      "Right": "./audio/17/fe_03_00040/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00041",
        "TestID": "17___fe_03_00041",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00041/stereo.wav",
      "Mono": "./audio/17/fe_03_00041/mono.wav",
      "Left": "./audio/17/fe_03_00041/0.wav",
      "Right": "./audio/17/fe_03_00041/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00057",
        "TestID": "17___fe_03_00057",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00057/stereo.wav",
      "Mono": "./audio/17/fe_03_00057/mono.wav",
      "Left": "./audio/17/fe_03_00057/0.wav",
      "Right": "./audio/17/fe_03_00057/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00059",
        "TestID": "17___fe_03_00059",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00059/stereo.wav",
      "Mono": "./audio/17/fe_03_00059/mono.wav",
      "Left": "./audio/17/fe_03_00059/0.wav",
      "Right": "./audio/17/fe_03_00059/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00066",
        "TestID": "17___fe_03_00066",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00066/stereo.wav",
      "Mono": "./audio/17/fe_03_00066/mono.wav",
      "Left": "./audio/17/fe_03_00066/0.wav",
      "Right": "./audio/17/fe_03_00066/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00069",
        "TestID": "17___fe_03_00069",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00069/stereo.wav",
      "Mono": "./audio/17/fe_03_00069/mono.wav",
      "Left": "./audio/17/fe_03_00069/0.wav",
      "Right": "./audio/17/fe_03_00069/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00078",
        "TestID": "17___fe_03_00078",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00078/stereo.wav",
      "Mono": "./audio/17/fe_03_00078/mono.wav",
      "Left": "./audio/17/fe_03_00078/0.wav",
      "Right": "./audio/17/fe_03_00078/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00081",
        "TestID": "17___fe_03_00081",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00081/stereo.wav",
      "Mono": "./audio/17/fe_03_00081/mono.wav",
      "Left": "./audio/17/fe_03_00081/0.wav",
      "Right": "./audio/17/fe_03_00081/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00084",
        "TestID": "17___fe_03_00084",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00084/stereo.wav",
      "Mono": "./audio/17/fe_03_00084/mono.wav",
      "Left": "./audio/17/fe_03_00084/0.wav",
      "Right": "./audio/17/fe_03_00084/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00089",
        "TestID": "17___fe_03_00089",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00089/stereo.wav",
      "Mono": "./audio/17/fe_03_00089/mono.wav",
      "Left": "./audio/17/fe_03_00089/0.wav",
      "Right": "./audio/17/fe_03_00089/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00090",
        "TestID": "17___fe_03_00090",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00090/stereo.wav",
      "Mono": "./audio/17/fe_03_00090/mono.wav",
      "Left": "./audio/17/fe_03_00090/0.wav",
      "Right": "./audio/17/fe_03_00090/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00091",
        "TestID": "17___fe_03_00091",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00091/stereo.wav",
      "Mono": "./audio/17/fe_03_00091/mono.wav",
      "Left": "./audio/17/fe_03_00091/0.wav",
      "Right": "./audio/17/fe_03_00091/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00095",
        "TestID": "17___fe_03_00095",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00095/stereo.wav",
      "Mono": "./audio/17/fe_03_00095/mono.wav",
      "Left": "./audio/17/fe_03_00095/0.wav",
      "Right": "./audio/17/fe_03_00095/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00096",
        "TestID": "17___fe_03_00096",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00096/stereo.wav",
      "Mono": "./audio/17/fe_03_00096/mono.wav",
      "Left": "./audio/17/fe_03_00096/0.wav",
      "Right": "./audio/17/fe_03_00096/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00097",
        "TestID": "17___fe_03_00097",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/17/fe_03_00097/stereo.wav",
      "Mono": "./audio/17/fe_03_00097/mono.wav",
      "Left": "./audio/17/fe_03_00097/0.wav",
      "Right": "./audio/17/fe_03_00097/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
]
}