var TestConfig = {
  "TestName": "Personality Labeling Survey",
  "RateScalePng": "img/alignment.png",
  "RateScaleBgPng": "img/scale_abs_background.png",
  "RateMinValue": 0,
  "RateMaxValue": 100,
  "RateDefaultValue":50,
  "ShowFileIDs": false,
  "ShowResults": false,
  "LoopByDefault": false,
  "EnableABLoop": true,
  "EnableOnlineSubmission": false,
  "BeaqleServiceURL": "/web_service/beaqleJS_Service.php",
  "SupervisorContact": "shoinoue@link.cuhk.edu.cn",
  "RandomizeTestOrder": true,
  "MaxTestsPerRun": 10000,
  "RequireMaxRating": false,
  "AudioRoot": "",
  "Testsets":
[
      {
        "Name": "fe_03_00005",
        "TestID": "10___fe_03_00005",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00005/stereo.wav",
      "Mono": "./audio/10/fe_03_00005/mono.wav",
      "Left": "./audio/10/fe_03_00005/0.wav",
      "Right": "./audio/10/fe_03_00005/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00007",
        "TestID": "10___fe_03_00007",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00007/stereo.wav",
      "Mono": "./audio/10/fe_03_00007/mono.wav",
      "Left": "./audio/10/fe_03_00007/0.wav",
      "Right": "./audio/10/fe_03_00007/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00008",
        "TestID": "10___fe_03_00008",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00008/stereo.wav",
      "Mono": "./audio/10/fe_03_00008/mono.wav",
      "Left": "./audio/10/fe_03_00008/0.wav",
      "Right": "./audio/10/fe_03_00008/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00018",
        "TestID": "10___fe_03_00018",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00018/stereo.wav",
      "Mono": "./audio/10/fe_03_00018/mono.wav",
      "Left": "./audio/10/fe_03_00018/0.wav",
      "Right": "./audio/10/fe_03_00018/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00019",
        "TestID": "10___fe_03_00019",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00019/stereo.wav",
      "Mono": "./audio/10/fe_03_00019/mono.wav",
      "Left": "./audio/10/fe_03_00019/0.wav",
      "Right": "./audio/10/fe_03_00019/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00021",
        "TestID": "10___fe_03_00021",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00021/stereo.wav",
      "Mono": "./audio/10/fe_03_00021/mono.wav",
      "Left": "./audio/10/fe_03_00021/0.wav",
      "Right": "./audio/10/fe_03_00021/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00026",
        "TestID": "10___fe_03_00026",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00026/stereo.wav",
      "Mono": "./audio/10/fe_03_00026/mono.wav",
      "Left": "./audio/10/fe_03_00026/0.wav",
      "Right": "./audio/10/fe_03_00026/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00028",
        "TestID": "10___fe_03_00028",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00028/stereo.wav",
      "Mono": "./audio/10/fe_03_00028/mono.wav",
      "Left": "./audio/10/fe_03_00028/0.wav",
      "Right": "./audio/10/fe_03_00028/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00030",
        "TestID": "10___fe_03_00030",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00030/stereo.wav",
      "Mono": "./audio/10/fe_03_00030/mono.wav",
      "Left": "./audio/10/fe_03_00030/0.wav",
      "Right": "./audio/10/fe_03_00030/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00032",
        "TestID": "10___fe_03_00032",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00032/stereo.wav",
      "Mono": "./audio/10/fe_03_00032/mono.wav",
      "Left": "./audio/10/fe_03_00032/0.wav",
      "Right": "./audio/10/fe_03_00032/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00033",
        "TestID": "10___fe_03_00033",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00033/stereo.wav",
      "Mono": "./audio/10/fe_03_00033/mono.wav",
      "Left": "./audio/10/fe_03_00033/0.wav",
      "Right": "./audio/10/fe_03_00033/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00041",
        "TestID": "10___fe_03_00041",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00041/stereo.wav",
      "Mono": "./audio/10/fe_03_00041/mono.wav",
      "Left": "./audio/10/fe_03_00041/0.wav",
      "Right": "./audio/10/fe_03_00041/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00059",
        "TestID": "10___fe_03_00059",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00059/stereo.wav",
      "Mono": "./audio/10/fe_03_00059/mono.wav",
      "Left": "./audio/10/fe_03_00059/0.wav",
      "Right": "./audio/10/fe_03_00059/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00064",
        "TestID": "10___fe_03_00064",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00064/stereo.wav",
      "Mono": "./audio/10/fe_03_00064/mono.wav",
      "Left": "./audio/10/fe_03_00064/0.wav",
      "Right": "./audio/10/fe_03_00064/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00078",
        "TestID": "10___fe_03_00078",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00078/stereo.wav",
      "Mono": "./audio/10/fe_03_00078/mono.wav",
      "Left": "./audio/10/fe_03_00078/0.wav",
      "Right": "./audio/10/fe_03_00078/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00084",
        "TestID": "10___fe_03_00084",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00084/stereo.wav",
      "Mono": "./audio/10/fe_03_00084/mono.wav",
      "Left": "./audio/10/fe_03_00084/0.wav",
      "Right": "./audio/10/fe_03_00084/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00088",
        "TestID": "10___fe_03_00088",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00088/stereo.wav",
      "Mono": "./audio/10/fe_03_00088/mono.wav",
      "Left": "./audio/10/fe_03_00088/0.wav",
      "Right": "./audio/10/fe_03_00088/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00089",
        "TestID": "10___fe_03_00089",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00089/stereo.wav",
      "Mono": "./audio/10/fe_03_00089/mono.wav",
      "Left": "./audio/10/fe_03_00089/0.wav",
      "Right": "./audio/10/fe_03_00089/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00092",
        "TestID": "10___fe_03_00092",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/10/fe_03_00092/stereo.wav",
      "Mono": "./audio/10/fe_03_00092/mono.wav",
      "Left": "./audio/10/fe_03_00092/0.wav",
      "Right": "./audio/10/fe_03_00092/1.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Left</b> Speaker)": "./audio/sample.wav",
      "<b>Openness</b>: intellectual, imaginative, independent-minded<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Conscientiousness</b>: orderly, responsible, dependable<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Extraversion</b>: talkative, assertive, energetic<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Agreeableness</b>: good-natured, cooperative, trustful<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
      "<b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression<br>(<b>Right</b> Speaker)": "./audio/sample.wav",
    }
  },
]
}