var TestConfig = {
  "TestName": "Personality Labeling Survey",
  "RateScalePng": "img/alignment.png",
  "RateScaleBgPng": "img/scale_abs_background.png",
  "RateMinValue": 0,
  "RateMaxValue": 100,
  "RateDefaultValue":50,
  "ShowFileIDs": false,
  "ShowResults": false,
  "LoopByDefault": false,
  "EnableABLoop": true,
  "EnableOnlineSubmission": false,
  "BeaqleServiceURL": "/web_service/beaqleJS_Service.php",
  "SupervisorContact": "shoinoue@link.cuhk.edu.cn",
  "RandomizeTestOrder": true,
  "MaxTestsPerRun": 10000,
  "RequireMaxRating": false,
  "AudioRoot": "",
  "Testsets":
[
      {
        "Name": "fe_03_00005",
        "TestID": "8___fe_03_00005",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00005/stereo.wav",
      "Mono": "./audio/8/fe_03_00005/mono.wav",
      "Left": "./audio/8/fe_03_00005/0.wav",
      "Right": "./audio/8/fe_03_00005/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00012",
        "TestID": "8___fe_03_00012",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00012/stereo.wav",
      "Mono": "./audio/8/fe_03_00012/mono.wav",
      "Left": "./audio/8/fe_03_00012/0.wav",
      "Right": "./audio/8/fe_03_00012/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00013",
        "TestID": "8___fe_03_00013",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00013/stereo.wav",
      "Mono": "./audio/8/fe_03_00013/mono.wav",
      "Left": "./audio/8/fe_03_00013/0.wav",
      "Right": "./audio/8/fe_03_00013/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00018",
        "TestID": "8___fe_03_00018",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00018/stereo.wav",
      "Mono": "./audio/8/fe_03_00018/mono.wav",
      "Left": "./audio/8/fe_03_00018/0.wav",
      "Right": "./audio/8/fe_03_00018/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00019",
        "TestID": "8___fe_03_00019",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00019/stereo.wav",
      "Mono": "./audio/8/fe_03_00019/mono.wav",
      "Left": "./audio/8/fe_03_00019/0.wav",
      "Right": "./audio/8/fe_03_00019/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00022",
        "TestID": "8___fe_03_00022",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00022/stereo.wav",
      "Mono": "./audio/8/fe_03_00022/mono.wav",
      "Left": "./audio/8/fe_03_00022/0.wav",
      "Right": "./audio/8/fe_03_00022/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00027",
        "TestID": "8___fe_03_00027",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00027/stereo.wav",
      "Mono": "./audio/8/fe_03_00027/mono.wav",
      "Left": "./audio/8/fe_03_00027/0.wav",
      "Right": "./audio/8/fe_03_00027/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00029",
        "TestID": "8___fe_03_00029",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00029/stereo.wav",
      "Mono": "./audio/8/fe_03_00029/mono.wav",
      "Left": "./audio/8/fe_03_00029/0.wav",
      "Right": "./audio/8/fe_03_00029/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00034",
        "TestID": "8___fe_03_00034",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00034/stereo.wav",
      "Mono": "./audio/8/fe_03_00034/mono.wav",
      "Left": "./audio/8/fe_03_00034/0.wav",
      "Right": "./audio/8/fe_03_00034/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00056",
        "TestID": "8___fe_03_00056",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00056/stereo.wav",
      "Mono": "./audio/8/fe_03_00056/mono.wav",
      "Left": "./audio/8/fe_03_00056/0.wav",
      "Right": "./audio/8/fe_03_00056/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00062",
        "TestID": "8___fe_03_00062",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00062/stereo.wav",
      "Mono": "./audio/8/fe_03_00062/mono.wav",
      "Left": "./audio/8/fe_03_00062/0.wav",
      "Right": "./audio/8/fe_03_00062/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00065",
        "TestID": "8___fe_03_00065",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00065/stereo.wav",
      "Mono": "./audio/8/fe_03_00065/mono.wav",
      "Left": "./audio/8/fe_03_00065/0.wav",
      "Right": "./audio/8/fe_03_00065/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00066",
        "TestID": "8___fe_03_00066",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00066/stereo.wav",
      "Mono": "./audio/8/fe_03_00066/mono.wav",
      "Left": "./audio/8/fe_03_00066/0.wav",
      "Right": "./audio/8/fe_03_00066/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00068",
        "TestID": "8___fe_03_00068",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00068/stereo.wav",
      "Mono": "./audio/8/fe_03_00068/mono.wav",
      "Left": "./audio/8/fe_03_00068/0.wav",
      "Right": "./audio/8/fe_03_00068/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00073",
        "TestID": "8___fe_03_00073",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00073/stereo.wav",
      "Mono": "./audio/8/fe_03_00073/mono.wav",
      "Left": "./audio/8/fe_03_00073/0.wav",
      "Right": "./audio/8/fe_03_00073/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00085",
        "TestID": "8___fe_03_00085",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00085/stereo.wav",
      "Mono": "./audio/8/fe_03_00085/mono.wav",
      "Left": "./audio/8/fe_03_00085/0.wav",
      "Right": "./audio/8/fe_03_00085/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00088",
        "TestID": "8___fe_03_00088",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00088/stereo.wav",
      "Mono": "./audio/8/fe_03_00088/mono.wav",
      "Left": "./audio/8/fe_03_00088/0.wav",
      "Right": "./audio/8/fe_03_00088/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00090",
        "TestID": "8___fe_03_00090",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00090/stereo.wav",
      "Mono": "./audio/8/fe_03_00090/mono.wav",
      "Left": "./audio/8/fe_03_00090/0.wav",
      "Right": "./audio/8/fe_03_00090/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
      {
        "Name": "fe_03_00096",
        "TestID": "8___fe_03_00096",
        "Text": "Please move the slider to input the alignment score between a speaker and a personality given 90-seconds dialog between two speakers. In Stereo Sound, you can hear different speakers from different ears. <b>Please double check the personality label and the speaker when you score.</b> We cover the following five personalities in this survey. <br><br> <b>Openness</b>: intellectual, imaginative, independent-minded; opposite term is <i>Closeness</i>. <br> <b>Conscientiousness</b>: orderly, responsible, dependable; opposite term is <i>Lack of direction</i>. <br> <b>Extraversion</b>: talkative, assertive, energetic; opposite term is <i>Introversion</i>. <br> <b>Agreeableness</b>: good-natured, cooperative, trustful; opposite term is <i>Antagonism</i>. <br> <b>Neuroticism</b>: emotional instability, irritability, anxiety, self-doubt, depression; opposite term is <i>Emotion stability</i>.  ",
        "Files": {
      "Stereo": "./audio/8/fe_03_00096/stereo.wav",
      "Mono": "./audio/8/fe_03_00096/mono.wav",
      "Left": "./audio/8/fe_03_00096/0.wav",
      "Right": "./audio/8/fe_03_00096/1.wav",
      "Openness<br>(Left Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Left Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Left Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Left Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Left Speaker)": "./audio/sample.wav",
      "Openness<br>(Right Speaker)": "./audio/sample.wav",
      "Conscientiousness<br>(Right Speaker)": "./audio/sample.wav",
      "Extraversion<br>(Right Speaker)": "./audio/sample.wav",
      "Agreeableness<br>(Right Speaker)": "./audio/sample.wav",
      "Neuroticism<br>(Right Speaker)": "./audio/sample.wav",
    }
  },
]
}